### PR TITLE
object: list objects v2

### PR DESCRIPTION
**Pull request by davies**

### CODE REVIEW

**Comment by zhijian-pro** [comment]
Object Distribution:   {1-1200}/{1-2000} ，a total of 2.4 million files

|      | Listv2 cost（delimit=/） |
| ---- | ------------------------ |
| S3   | 154.941455ms             |
| OSS  | 2.462854489s             |
| TOS  | 5.093987835s             |
| OBS  | 4.07782405s              |
| COS  | 414.096736ms             |

**Comment by zhijian-pro** [comment]
|            | There are 1 million files in the directory: {1-1000000}file  |                 |
| ---------- | ------------------------------------------------------------ | --------------- |
|            | List with delimiter                                          |                 |
|            | listv1                                                       | listv2          |
| minio      | 15m6.116118689s                                              | 8m47.8935864s   |
| gateway_v1 | 30s                                                          | 21s             |
| gateway_v2 | 29s                                                          | 20s             |
|            |                                                              |                 |
|            | List without delimiter                                       |                 |
|            | listv1                                                       | listv2          |
| minio      | 16m31.905750662s                                             | 9m35.015635738s |
| gateway_v1 | 29s                                                          | 20s             |
| gateway_v2 | 30s                                                          | 20s             |
|            |                                                              |                 |
|            |                                                              |                 |
|            | There are 1 million files in the directory, and each subdirectory also contains one file：{1-1000000}_dir/file1 |                 |
|            | List with delimiter                                          |                 |
|            | listv1                                                       | listv2          |
| minio      | 11m27.925511683s                                             | 4m10.883067834s |
| gateway_v1 | 2m50s                                                        | 2m48s           |
| gateway_v2 | 12s                                                          | 9s              |
|            |                                                              |                 |
|            | List without delimiter                                       |                 |
|            | listv1                                                       | listv2          |
| minio      | 20m40.149399176s                                             | 12m36.0965083s  |
| gateway_v1 | 4m53s                                                        | 4m50s           |
| gateway_v2 | 2m54s                                                        | 2m50s           |

**Comment by liuzhijun** [comment]
how many the size of the total meta data?

**Comment by zhijian-pro** [comment]
@liuzhijun I use Redis for testing, but I didn't pay attention to the memory usage situation.

**Pull request merged**
