### PR TITLE
vfs: record plock owner and use it instead of the one from FUSE

### PR DESCRIPTION
**Pull request by SandyXSD**

### CODE REVIEW

**Comment by SandyXSD** [comment]
It's possible that FUSE passes different lock owners for `setlk` and `flush`, even though they are called on the same file handler. In this case, plocks are not released as expected when the file is closed.

Tested on Ubuntu 20.04 with kernel 5.4.0-96-generic, juicefs version 1.1.0-dev+2022-08-31.1719f888
Steps:
```
$ qemu-img create -f qcow2 -F qcow2 -o backing_file=CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2 test.qcow2
$ qemu-img commit test.qcow2
# then the backing file is wrongly locked
$ qemu-img info CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2
```

**Comment by SandyXSD** [comment]
Accesslog:
```
2022.08.30 16:20:56.545863 [uid:0,gid:0,pid:340775] open (9223372032559808513): OK [fh:1] <0.000054>
2022.08.30 16:20:58.489090 [uid:0,gid:0,pid:340780] getattr (2): OK (2,[drwxr-xr-x:0040755,2,0,0,1661826416,1661847619,1661847619,4096]) <0.000255>
2022.08.30 16:20:58.489323 [uid:0,gid:0,pid:340780] lookup (2,eden-cfp2.qcow2): OK (302,[-rw-r--r--:0100644,1,0,0,1661835981,1661847588,1661847588,262144]) <0.000179>
2022.08.30 16:20:58.489620 [uid:0,gid:0,pid:340780] open (302): OK [fh:2] <0.000225>
2022.08.30 16:20:58.489778 [uid:0,gid:0,pid:340780] flush (302,2,22A0CDE59E8A153A): OK <0.000002>
2022.08.30 16:20:58.489843 [uid:0,gid:0,pid:0] release (302,2): OK <0.000010>
2022.08.30 16:20:58.490636 [uid:0,gid:0,pid:340780] open (302): OK [fh:3] <0.000183>
2022.08.30 16:20:58.491005 [uid:0,gid:0,pid:340780] statfs (302): OK (731684864,1125899175157760,13,10485760) <0.000224>
2022.08.30 16:20:58.492126 [uid:0,gid:0,pid:340782] read (302,16384,0): OK (16384) <0.000360>
2022.08.30 16:20:58.501797 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,100,100,R,false,340780): OK <0.009445>
2022.08.30 16:20:58.508799 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,101,101,R,false,340780): OK <0.006847>
2022.08.30 16:20:58.523497 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,103,103,R,false,340780): OK <0.014540>
2022.08.30 16:20:58.531577 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,201,201,R,false,340780): OK <0.007902>
2022.08.30 16:20:58.544675 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,203,203,R,false,340780): OK <0.012915>
2022.08.30 16:20:58.545086 [uid:0,gid:0,pid:340780] getlk (302,3,9F9E9AB7EA4C62EF): OK (0,0,U,0) <0.000211>
2022.08.30 16:20:58.545397 [uid:0,gid:0,pid:340780] getlk (302,3,9F9E9AB7EA4C62EF): OK (0,0,U,0) <0.000182>
2022.08.30 16:20:58.545630 [uid:0,gid:0,pid:340780] getlk (302,3,9F9E9AB7EA4C62EF): OK (0,0,U,0) <0.000118>
2022.08.30 16:20:58.545854 [uid:0,gid:0,pid:340780] getlk (302,3,9F9E9AB7EA4C62EF): OK (0,0,U,0) <0.000111>
2022.08.30 16:20:58.546067 [uid:0,gid:0,pid:340780] getlk (302,3,9F9E9AB7EA4C62EF): OK (0,0,U,0) <0.000108>
2022.08.30 16:20:58.546476 [uid:0,gid:0,pid:340782] read (302,4096,196608): OK (4096) <0.000013>
2022.08.30 16:20:58.546958 [uid:0,gid:0,pid:340782] read (302,65536,65536): OK (65536) <0.000045>
2022.08.30 16:20:58.547805 [uid:0,gid:0,pid:340780] lookup (2,CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2): OK (3,[-rw-r--r--:0100644,1,0,0,1661826419,1661826420,1661826424,730369024]) <0.000229>
2022.08.30 16:20:58.548009 [uid:0,gid:0,pid:340780] open (3): OK [fh:4] <0.000150>
2022.08.30 16:20:58.548158 [uid:0,gid:0,pid:340780] flush (3,4,22A0CDE59E8A153A): OK <0.000001>
2022.08.30 16:20:58.548204 [uid:0,gid:0,pid:0] release (3,4): OK <0.000009>
2022.08.30 16:20:58.548522 [uid:0,gid:0,pid:340780] open (3): OK [fh:5] <0.000143>
2022.08.30 16:20:58.548895 [uid:0,gid:0,pid:340780] statfs (3): OK (731684864,1125899175157760,13,10485760) <0.000215>
2022.08.30 16:20:58.561234 [uid:0,gid:0,pid:340780] setlk (3,5,4EFBA37B80DA9CEC,100,100,R,false,340780): OK <0.012058>
2022.08.30 16:20:58.575742 [uid:0,gid:0,pid:340780] setlk (3,5,4EFBA37B80DA9CEC,201,201,R,false,340780): OK <0.014339>
2022.08.30 16:20:58.584182 [uid:0,gid:0,pid:340780] setlk (3,5,4EFBA37B80DA9CEC,203,203,R,false,340780): OK <0.008213>
2022.08.30 16:20:58.584476 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000153>
2022.08.30 16:20:58.584684 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000090>
2022.08.30 16:20:58.584859 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000082>
2022.08.30 16:20:58.586069 [uid:0,gid:0,pid:340782] read (3,16384,0): OK (16384) <0.000855>
2022.08.30 16:20:58.590530 [uid:0,gid:0,pid:340782] read (3,4096,196608): OK (4096) <0.000012>
2022.08.30 16:20:58.591202 [uid:0,gid:0,pid:340782] read (3,65536,65536): OK (65536) <0.000018>
2022.08.30 16:20:58.593284 [uid:0,gid:0,pid:340780] open (3): OK [fh:6] <0.000207>
2022.08.30 16:20:58.608240 [uid:0,gid:0,pid:340780] setlk (3,5,4EFBA37B80DA9CEC,101,101,R,false,340780): OK <0.014829>
2022.08.30 16:20:58.617684 [uid:0,gid:0,pid:340780] setlk (3,5,4EFBA37B80DA9CEC,103,103,R,false,340780): OK <0.009258>
2022.08.30 16:20:58.618028 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000183>
2022.08.30 16:20:58.618322 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000120>
2022.08.30 16:20:58.618524 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000078>
2022.08.30 16:20:58.618722 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000091>
2022.08.30 16:20:58.618892 [uid:0,gid:0,pid:340780] getlk (3,5,4EFBA37B80DA9CEC): OK (0,0,U,0) <0.000083>
2022.08.30 16:20:58.635326 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,100,100,R,false,340780): OK <0.016339>
2022.08.30 16:20:58.645492 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,101,101,R,false,340780): OK <0.009973>
2022.08.30 16:20:58.658153 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,103,103,R,false,340780): OK <0.012485>
2022.08.30 16:20:58.692913 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,201,201,R,false,340780): OK <0.034585>
2022.08.30 16:20:58.712134 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,203,203,R,false,340780): OK <0.019020>
2022.08.30 16:20:58.712634 [uid:0,gid:0,pid:340780] flush (3,5,22A0CDE59E8A153A): OK <0.000307>
2022.08.30 16:20:58.712694 [uid:0,gid:0,pid:0] release (3,5): OK <0.000012>
2022.08.30 16:20:58.714095 [uid:0,gid:0,pid:340780] getattr (302): OK (302,[-rw-r--r--:0100644,1,0,0,1661835981,1661847588,1661847588,262144]) <0.000170>
2022.08.30 16:20:58.714296 [uid:0,gid:0,pid:340782] read (302,65536,131072): OK (65536) <0.000019>
2022.08.30 16:20:58.715772 [uid:0,gid:0,pid:340782] write (302,8,72,3): OK <0.000044>
2022.08.30 16:20:58.738099 [uid:0,gid:0,pid:340782] fsync (302,1): OK <0.021905>
2022.08.30 16:20:58.746251 [uid:0,gid:0,pid:340782] fallocate (302,3,196608,65536): OK <0.007683>
2022.08.30 16:20:58.757846 [uid:0,gid:0,pid:340782] fallocate (302,0,196608,65536): OK <0.011517>
2022.08.30 16:20:58.767506 [uid:0,gid:0,pid:340782] fallocate (302,3,65536,196608): OK <0.009171>
2022.08.30 16:20:58.778315 [uid:0,gid:0,pid:340782] fallocate (302,0,65536,196608): OK <0.010715>
2022.08.30 16:20:58.778862 [uid:0,gid:0,pid:340782] write (302,20,40,3): OK <0.000030>
2022.08.30 16:20:58.787563 [uid:0,gid:0,pid:340782] fsync (302,1): OK <0.008280>
2022.08.30 16:20:58.788119 [uid:0,gid:0,pid:340782] write (302,8,65536,3): OK <0.000048>
2022.08.30 16:20:58.804695 [uid:0,gid:0,pid:340782] fsync (302,1): OK <0.016225>
2022.08.30 16:20:58.805451 [uid:0,gid:0,pid:340782] getattr (302): OK (302,[-rw-r--r--:0100644,1,0,0,1661835981,1661847658,1661847658,262144]) <0.000228>
2022.08.30 16:20:58.805810 [uid:0,gid:0,pid:340782] read (302,65536,131072): OK (65536) <0.000278>
2022.08.30 16:20:58.806376 [uid:0,gid:0,pid:340782] write (302,65536,131072,3): OK <0.000028>
2022.08.30 16:20:58.833975 [uid:0,gid:0,pid:340782] fsync (302,1): OK <0.026738>
2022.08.30 16:20:58.834643 [uid:0,gid:0,pid:340782] write (302,65536,0,3): OK <0.000043>
2022.08.30 16:20:58.835245 [uid:0,gid:0,pid:340780] getattr (302): OK (302,[-rw-r--r--:0100644,1,0,0,1661835981,1661847658,1661847658,262144]) <0.000218>
2022.08.30 16:20:58.852792 [uid:0,gid:0,pid:340782] setattr (302,0x248,[size=262144]): OK (302,[-rw-r--r--:0100644,1,0,0,1661835981,1661847658,1661847658,262144]) <0.017394>
2022.08.30 16:20:58.853446 [uid:0,gid:0,pid:340782] fsync (302,1): OK <0.000006>
2022.08.30 16:20:58.873963 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,100,100,U,false,0): OK <0.019928>
2022.08.30 16:20:58.885676 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,101,101,U,false,0): OK <0.011498>
2022.08.30 16:20:58.905853 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,103,103,U,false,0): OK <0.020002>
2022.08.30 16:20:58.931749 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,201,201,U,false,0): OK <0.025695>
2022.08.30 16:20:58.945955 [uid:0,gid:0,pid:340780] setlk (302,3,9F9E9AB7EA4C62EF,203,203,U,false,0): OK <0.014030>
2022.08.30 16:20:58.946744 [uid:0,gid:0,pid:340780] flush (302,3,22A0CDE59E8A153A): OK <0.000321>
2022.08.30 16:20:58.946795 [uid:0,gid:0,pid:0] release (302,3): OK <0.000006>
2022.08.30 16:20:58.971296 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,100,100,U,false,0): OK <0.023409>
2022.08.30 16:20:58.980960 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,101,101,U,false,0): OK <0.009445>
2022.08.30 16:20:59.006969 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,103,103,U,false,0): OK <0.025850>
2022.08.30 16:20:59.020018 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,201,201,U,false,0): OK <0.012869>
2022.08.30 16:20:59.032500 [uid:0,gid:0,pid:340780] setlk (3,6,8E6966E2687BDBB5,203,203,U,false,0): OK <0.012305>
2022.08.30 16:20:59.033163 [uid:0,gid:0,pid:340780] flush (3,6,22A0CDE59E8A153A): OK <0.000275>
2022.08.30 16:20:59.033215 [uid:0,gid:0,pid:0] release (3,6): OK <0.000007>
```

**Comment by SandyXSD** [comment]
Part of strace result:
```
openat(AT_FDCWD, "eden-cfp2.qcow2", O_RDWR|O_CLOEXEC) = 9                                                                              [9/1819]
fcntl(9, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
fcntl(9, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=200, l_len=1, l_pid=0}) = 0
fcntl(9, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=201, l_len=1, l_pid=0}) = 0
fcntl(9, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=203, l_len=1, l_pid=0}) = 0
fcntl(9, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=101, l_len=1, l_pid=0}) = 0
fcntl(9, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=103, l_len=1, l_pid=0}) = 0
openat(AT_FDCWD, "CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 10
close(10)                               = 0
openat(AT_FDCWD, "CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2", O_RDONLY|O_CLOEXEC) = 10
fcntl(10, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(10, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(10, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=200, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=101, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=103, l_len=1, l_pid=0}) = 0
openat(AT_FDCWD, "CentOS-Stream-ec2-8-20200113.0.x86_64.qcow2", O_RDWR|O_CLOEXEC) = 11
fcntl(10, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(10, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=200, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=201, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=203, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=101, l_len=1, l_pid=0}) = 0
fcntl(10, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=103, l_len=1, l_pid=0}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
close(10)                               = 0
fcntl(9, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(9, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
close(9)                                = 0
fcntl(11, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(11, F_OFD_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
close(11)
```

**Comment by SandyXSD** [comment]
More test results:
Call `setlk` with `F_OFD_SETLK` and `flock` on the same fh: same owner for two locks
```
2022.08.31 15:08:32.087621 [uid:0,gid:0,pid:541987] open (402): OK [fh:5] <0.000133>
2022.08.31 15:08:32.087659 [uid:0,gid:0,pid:541983] open (402): OK [fh:6] <0.000149>
2022.08.31 15:08:32.104528 [uid:0,gid:0,pid:541987] setlk (402,5,FF8352F4061D70D2,0,9223372036854775807,R,false,541983): OK <0.016843>
2022.08.31 15:08:32.123805 [uid:0,gid:0,pid:541987] flock (402,5,FF8352F4061D70D2,LOCKSH,true): OK <0.019193>
2022.08.31 15:08:32.133413 [uid:0,gid:0,pid:541983] setlk (402,6,8A56FBDC123D8D8F,0,9223372036854775807,R,false,541983): OK <0.045264>
2022.08.31 15:08:32.157513 [uid:0,gid:0,pid:541983] flock (402,6,8A56FBDC123D8D8F,LOCKSH,true): OK <0.024016>
2022.08.31 15:08:33.124476 [uid:0,gid:0,pid:541985] flush (402,5,0C465EC7F83DF410): OK <0.000341>
2022.08.31 15:08:33.135486 [uid:0,gid:0,pid:0] release (402,5): OK <0.010964>
2022.08.31 15:08:33.158690 [uid:0,gid:0,pid:541983] flush (402,6,0C465EC7F83DF410): OK <0.000411>
2022.08.31 15:08:33.166630 [uid:0,gid:0,pid:0] release (402,6): OK <0.007881>
```

Call `setlk` with `F_SETLK` and `flock` on the same fh: different owners for two locks
```
2022.08.31 15:09:34.325607 [uid:0,gid:0,pid:542205] open (402): OK [fh:8] <0.000116>
2022.08.31 15:09:34.325621 [uid:0,gid:0,pid:542209] open (402): OK [fh:9] <0.000125>
2022.08.31 15:09:34.343246 [uid:0,gid:0,pid:542205] setlk (402,8,7045541A8BCA1305,0,9223372036854775807,R,false,542205): OK <0.017580>
2022.08.31 15:09:34.343802 [uid:0,gid:0,pid:542209] setlk (402,9,7045541A8BCA1305,0,9223372036854775807,R,false,542205): OK <0.018121>
2022.08.31 15:09:34.351835 [uid:0,gid:0,pid:542205] flock (402,8,FF761F3D959BA0DA,LOCKSH,true): OK <0.008500>
2022.08.31 15:09:34.359715 [uid:0,gid:0,pid:542209] flock (402,9,32660335B023FDF9,LOCKSH,true): OK <0.015835>
2022.08.31 15:09:35.366066 [uid:0,gid:0,pid:542207] flush (402,8,7045541A8BCA1305): OK <0.013459>
2022.08.31 15:09:35.366495 [uid:0,gid:0,pid:542209] flush (402,9,7045541A8BCA1305): OK <0.005828>
2022.08.31 15:09:35.379165 [uid:0,gid:0,pid:0] release (402,8): OK <0.013036>
2022.08.31 15:09:35.391998 [uid:0,gid:0,pid:0] release (402,9): OK <0.025430>
```

**Review by davies — APPROVED** [review]

**Pull request merged**
