### PR TITLE
metadata: should not skip error if open a file not exist

### PR DESCRIPTION
**Pull request by chiyutianyi**
The original implements will always return ok if open a file that does
not exist.

Another unresolved problem is that if an "attr" is given with "Full=true", even
if they do not match, the "GetAttr()" call will still be skipped. But
this does not seem to be a serious problem.

Signed-off-by: 炽天 <hanxin.hx@alibaba-inc.com>

### CODE REVIEW

**Comment by chiyutianyi** [comment]
By the way, I found that there are many duplicate implementations in redis.go, sql.go, tkv.go, such as Access(), Open(), Mkdir(), etc., should there be a default implementation?

**Review by davies — APPROVED** [review]

**Comment by davies** [comment]
@chiyutianyi It's better to reset attr.Full to false before OpenCheck(), please add that also?

**Comment by davies** [comment]
> By the way, I found that there are many duplicate implementations in redis.go, sql.go, tkv.go, such as Access(), Open(), Mkdir(), etc., should there be a default implementation?

Yes, we will look into that.

**Comment by chiyutianyi** [comment]
> @chiyutianyi It's better to reset attr.Full to false before OpenCheck(), please add that also?

OK, I will do that. 

However, the reason why I did not fix the problem before is that, the current code does not cause actual problems in " vfs.go". It is just that during the execution of the test cases, it may produce inaccurate situations. 

In addition to the inner openfiles cache, I also like an external cache wrapper to make "GetAttr()" interact with "Open()". If we do this, resetting attr.Full may not be the best choice.

**Pull request merged**
