### PR TITLE
Use miniredis to avoid starting a redis server for unit tests

### PR DESCRIPTION
**Pull request by suzaku**

### CODE REVIEW

**Comment by davies** [comment]
This is cool!

One question: Does the miniredis have the same sematics comparing to the real redis? For example, the transaction support. If not, it may hide some bugs.

Since it's pretty light way to start redis-server,  and we have not run into problem, so I'd like to keep it.

Once thing we can do, is to launch a redis process rather than depending on external one.

**Comment by davies** [comment]
Also, we need to have more tests to cover the cases on retrying failed request, that will require a real redis.

**Comment by suzaku** [comment]
If we separate unit tests and integration tests, is it OK to use a lightweight mock for unit tests?

**Comment by suzaku** [comment]
Or we can use something like docker-compose and make the test running container depend on a redis container. Either way, the main goal is to make it easier to run tests in the development environment.

**Comment by davies** [comment]
Miniredis support transactions, that's good. Then we may add checking redis config, which use `INFO` and `CONFIG`, they are not supported by Miniredis. so we still need the real redis to run unit test.

Do you have difficulty to install redis-server in your developing enviroment?

**Comment by suzaku** [comment]
No, I can easily start a redis-server with Docker.

**Comment by davies** [comment]
Thanks, we can revisit this in future.

**Pull request closed without merging**
