### PR TITLE
remove duplicated docs on JuiceFS CSI Driver

### PR DESCRIPTION
**Pull request by timfeirg**
CSI Driver docs has been refurbished, lets maintain csi docs in one place.

the "Mount JuiceFS in the container" part will be re-introduced in CSI docs later.

### CODE REVIEW

**Comment by zwwhdls** [comment]
I suggest to keep CSI usage and hostPath usage in this doc and keep a link to CSI docs. About `Mount JuiceFS in the container`, I don't know if it's a common usage in Kubernetes. What do you think? @timfeirg

**Comment by timfeirg** [comment]
I wish all Kubernetes related usage should reside in CSI documentation, including practices like "Mount JuiceFS in the container" or hostPath, although they aren't really under the CSI realm, they are close related to Kubernetes. I want to keep all Kubernetes topics under CSI docs to reduce maintenance.

After that, we can leave references in CE/EE docs so that users don't get lost.

**Comment by davies** [comment]
K8S is just one way of using containers, let's replace the CSI part as a link and keep others here.

**Comment by timfeirg** [comment]
"Mount JuiceFS in the container" is preserved, this pr only deletes CSI tutorials.

**Pull request merged**
