### PR TITLE
show progress status for list slice

### PR DESCRIPTION
**Pull request by zhijian-pro**
#336 
@davies 
I didn't understand the way you said to handle it  `updateProgress func (n int64)`
In the end,  I decided to wrap the progress logic inside the list slice and add the `showProgress bool` parameter to the `ListSlices` interface.  
When we need to show the progress, showProgress  passed true.
I think this makes the `ListSlices` interface simpler and clearer, different metadata types can be implemented differently if needed, and it is not bound to mbp.

Kapture 2021-07-24 at 17 44 34

### CODE REVIEW

**Comment by davies** [comment]
I meant to change the `ListSlices` to

```
ListSlices(ctx Context, slices *[]Slice, delete bool, showProgress func(n int64)) syscall.Errno {
    for {
        // found a slice
        if showProgress != nil {
           showProgress(1)
        }
    }
}
```

In fsck or gc, we can implement the progress bar:
```
		process := mpb.New(mpb.WithWidth(32), mpb.WithOutput(logger.WriterLevel(logrus.InfoLevel)))
		bar := process.AddSpinner(total,
			mpb.PrependDecorators(
				// display our name with one space on the right
				decor.Name("listed slices counter:", decor.WC{W: len("listed slices counter:") + 1, C: decor.DidentRight}),
				decor.CurrentNoUnit("%d"),
			),
			mpb.BarFillerClearOnComplete(),
		)
                var total int64
                r := m.ListSlices(c, &slices, false, func(n int64){
                       total += n
                       bar.SetTotal(total+2048, false)
                       bar.Increment() 
                })
                bar.SetTotal(-1, true)
		process.Wait()
```

**Comment by zhijian-pro** [comment]
@davies Sorry, I'm still an inexperienced programmer, it's true that functions are better as parameters, I've changed the type of showProgress to func() , it doesn't need an n parameter to complete the task

**Review by davies — APPROVED** [review]

**Comment by davies** [comment]
@zhijian-pro Looks great, thanks!

**Comment by zhijian-pro** [comment]
@davies  I should be thanking you, I learned a lot, I will continue to contribute to juicefs in the future.

**Pull request merged**
