### PR TITLE
badger: disable badger metrics

### LINKED ISSUE #4971: Disable BadgerDB metrics logs
**What would you like to be added**:
https://github.com/dgraph-io/badger/blob/a09e9837cd271284f43fba45b94c2847a4a58901/options.go#L148
Set to `false`

**Why is this needed**:
Avoid "spam" useless log lines like:

> badger[932266] <INFO>: Block cache metrics: hit: 6030802 miss: 2430889 keys-added: 414076 keys-updated: 113041 keys-evicted: 353296 cost-added: 1809361703 cost-evicted: 1540927492 sets-dropped: 0 sets-rejected: 1883285 gets-dropped: 21888 gets-kept: 8439168 gets-total: 8461691 hit-ratio: 0.71 [logger.go:46]

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #4971

### CODE REVIEW

**Comment by solracsf** [comment]
@zhijian-pro despite this PR, Block cache metrics still printed on logs on JuiceFS v1.3.0.

**Comment by zhijian-pro** [comment]
@solracsf  Does "Block cache metrics" refer to badger's metrics?

**Comment by solracsf** [comment]
@zhijian-pro :

> juicefs[375967]: 2025/08/05 09:47:46.035640 badger[375967] <INFO>: Block cache metrics: hit: 948432 miss: 291865 keys-added: 120191 keys-updated: 4594 keys-evicted: 58938 cost-added: 525451540 cost-evicted: 257018154 sets-dropped: 0 sets-rejected: 167026 gets-dropped: 3520 gets-kept: 1236480 gets-total: 1240297 hit-ratio: 0.76 [Infof@logger.go:46]

```
# juicefs --version
juicefs version 1.3.0+2025-07-03.30190ca
```

**Comment by zhijian-pro** [comment]
image
@solracsf  It seems there is no way to turn off this log.
Perhaps you need to go to badger's community and suggest that they modify the log level

**Comment by solracsf** [comment]
Ok thanks.

**Pull request merged**
