### PR TITLE
update grafana dashboard template

### PR DESCRIPTION
**Pull request by yuhr123**
~Please pay attention to the variables and names in the template.~
Please help review the variable names in the template.

### CODE REVIEW

**Comment by davies** [comment]
What's the requirement for Grafana?

**Comment by yuhr123** [comment]
> What's the requirement for Grafana?

image

As shown in the image, when uploading a template on the Grafana Dashboard platform, it displays this error message. I didn't find a clear syntax explanation based on the link provided on the page. 

However, I was able to upload the template to the public repository after rebuilding and exporting it on the latest version of Grafana.

It is possible that the reason is that our current template was exported based on an older version of Grafana.

**Comment by davies** [comment]
User may still use older version of Grafana, they should be able to use this template.

**Comment by yuhr123** [comment]
For compatibility considerations, we will not overwrite the existing template files for now.

**Pull request closed without merging**
