### PR TITLE
chunk: add an env "JFS_DROP_OSCACHE" to drop page cache for block cache

### PR DESCRIPTION
**Pull request by SandyXSD**

### CODE REVIEW

**Comment by polyrabbit** [comment]
Which scenario it is used for, and why not dropping cache after flushing stage blocks?

**Comment by jiefenghuang** [comment]
> Which scenario it is used for, and why not dropping cache after flushing stage blocks?

1. reduce page cache usage
2. upcoming uploads requirement

**Comment by polyrabbit** [comment]
I know it reduces page cache. The question is in which scenario user needs to turn on this flag, like avoiding OOM caused by page cache we encountered [before](https://github.com/juicedata/juicefs/pull/4781)?

**Comment by lidaohang** [comment]
mark

**Pull request merged**
