### PR TITLE
Deploy using latest CSI driver

### PR DESCRIPTION
**Pull request by solracsf**

### CODE REVIEW

**Comment by zwwhdls** [comment]
Hi @solracsf , juicefs image has been separated from CSI driver. Sorry for not updating docs and thanks for helping doing this. You can use `juicedata/mount:latest` instead. Thanks!

**Comment by solracsf** [comment]
Should i ammend or close the PR?

**Comment by zwwhdls** [comment]
@solracsf Just modify it and it will be fine, thank you.

**Comment by solracsf** [comment]
Done.

**Pull request merged**
